import { useMemo, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Feather, FontAwesome6 } from '@expo/vector-icons';
import * as DocumentPicker from 'expo-document-picker';
import { useTranslation } from 'react-i18next';
import { colors } from '@/constants/theme';
import { createMedia } from '@/lib/api';
import { getCurrentUser } from '@/lib/session';

type Asset = { uri: string; name: string; mimeType: string };
const audioTypes = [{ value: 'music', icon: 'music' }, { value: 'education', icon: 'graduation-cap' }, { value: 'documentary', icon: 'microphone-lines' }, { value: 'comedy', icon: 'face-laugh-beam' }] as const;

export default function CreateAudioScreen() {
  const { t } = useTranslation();
  const [step, setStep] = useState(1); const [audio, setAudio] = useState<Asset | null>(null); const [cover, setCover] = useState<Asset | null>(null);
  const [type, setType] = useState('music'); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [author, setAuthor] = useState(''); const [premium, setPremium] = useState(false); const [price, setPrice] = useState(''); const [submitting, setSubmitting] = useState(false);
  const pick = async (kind: 'audio' | 'cover') => { const result = await DocumentPicker.getDocumentAsync({ type: kind === 'audio' ? ['audio/mpeg', 'audio/mp4', 'audio/wav', 'audio/aac', 'audio/*'] : ['image/png', 'image/jpeg'], copyToCacheDirectory: true }); if (!result.canceled && result.assets[0]) { const a = result.assets[0]; const picked = { uri: a.uri, name: a.name ?? `talaplus-${kind}-${Date.now()}`, mimeType: a.mimeType ?? (kind === 'audio' ? 'audio/mpeg' : 'image/jpeg') }; kind === 'audio' ? setAudio(picked) : setCover(picked); } };
  const next = () => { if (step === 1 && !audio) return Alert.alert(t('requiredAudioTitle'), t('requiredAudioBody')); if (step === 3 && (!title.trim() || !description.trim() || !author.trim())) return Alert.alert(t('incompleteInfoTitle'), t('incompleteAudioInfoBody')); setStep((value) => Math.min(5, value + 1)); };
  const publish = async () => { if (!audio) return; try { setSubmitting(true); const form = new FormData(); [['type', type], ['is_audio', '1'], ['media_title', title], ['title', title], ['media_description', description], ['description', description], ['author_names', author], ['is_free', premium ? '0' : '1'], ['price', premium ? price || '0' : '0'], ['user_id', getCurrentUser().id]].forEach(([k,v]) => form.append(k,v)); form.append('media_file', { uri: audio.uri, name: audio.name, type: audio.mimeType } as unknown as Blob); if (cover) form.append('cover_file', { uri: cover.uri, name: cover.name, type: cover.mimeType } as unknown as Blob); await createMedia(form); Alert.alert(t('audioPublished'), t('audioPublishedBody'), [{ text: t('ok'), onPress: () => router.back() }]); } catch (e) { Alert.alert(t('publicationImpossible'), e instanceof Error ? e.message : t('publicationFallbackError')); } finally { setSubmitting(false); } };
  return <SafeAreaView style={styles.container}><View style={styles.header}><Pressable onPress={() => step === 1 ? router.back() : setStep(step - 1)}><Feather name="arrow-left" size={24} color={colors.text}/></Pressable><View><Text style={styles.headerTitle}>{t('publishAudio')}</Text><Text style={styles.step}>{step}. {t(['chooseAudio','chooseChannel','audioInfo','accessAndPrice','previewAndPublish'][step - 1])}</Text></View><View style={{width:24}}/></View><ScrollView contentContainerStyle={styles.content}>{step === 1 && <><Text style={styles.title}>{t('selectAudio')}</Text><Pressable style={styles.picker} onPress={() => pick('audio')}><Feather name="music" size={50} color={colors.primary}/><Text style={styles.pickerText}>{audio?.name ?? t('chooseAudioFile')}</Text></Pressable></>}{step === 2 && <><Text style={styles.title}>{t('chooseChannel')}</Text><View style={styles.grid}>{audioTypes.map(item => <Pressable key={item.value} onPress={() => setType(item.value)} style={[styles.type, type === item.value && styles.typeSelected]}><FontAwesome6 name={item.icon} size={27} color={colors.text}/><Text style={styles.typeText}>{t(item.value === 'music' ? 'music' : item.value === 'education' ? 'education' : item.value === 'documentary' ? 'documentaries' : 'comedy')}</Text></Pressable>)}</View></>}{step === 3 && <><Pressable style={styles.cover} onPress={() => pick('cover')}>{cover ? <Image source={{uri: cover.uri}} style={styles.coverImage}/> : <><Feather name="image" size={30} color={colors.primary}/><Text style={styles.muted}>{t('addAudioCover')}</Text></>}</Pressable><TextInput value={title} onChangeText={setTitle} placeholder={t('audioTitle')} placeholderTextColor={colors.muted} style={styles.input}/><TextInput value={description} onChangeText={setDescription} placeholder={t('description')} placeholderTextColor={colors.muted} style={[styles.input, styles.area]} multiline/><TextInput value={author} onChangeText={setAuthor} placeholder={t('audioAuthor')} placeholderTextColor={colors.muted} style={styles.input}/></>}{step === 4 && <><View style={styles.row}><View><Text style={styles.label}>{t('free')}</Text><Text style={styles.muted}>{t('audioAccessHint')}</Text></View><Switch value={!premium} onValueChange={v => setPremium(!v)}/></View>{premium && <TextInput value={price} onChangeText={setPrice} keyboardType="decimal-pad" placeholder={t('price')} placeholderTextColor={colors.muted} style={styles.input}/>}</>}{step === 5 && <View style={styles.preview}>{cover ? <Image source={{uri:cover.uri}} style={styles.previewImage}/> : <Feather name="music" size={56} color={colors.primary}/>}<Text style={styles.title}>{title || t('audio')}</Text><Text style={styles.muted}>{author}</Text></View>}<Pressable style={styles.button} onPress={step === 5 ? publish : next} disabled={submitting}><Text style={styles.buttonText}>{submitting ? t('sending') : step === 5 ? t('publish') : `${t('next')} (${step + 1})`}</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container:{flex:1,backgroundColor:colors.background},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:16},headerTitle:{color:colors.text,fontWeight:'900',textAlign:'center'},step:{color:colors.primary,fontWeight:'800',fontSize:12,textAlign:'center',marginTop:4},content:{padding:16,gap:12},title:{color:colors.text,fontSize:18,fontWeight:'900'},picker:{height:280,borderRadius:8,alignItems:'center',justifyContent:'center',gap:14,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.border},pickerText:{color:colors.text,fontWeight:'800'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},type:{width:'48%',height:108,alignItems:'center',justifyContent:'center',gap:10,borderRadius:8,backgroundColor:colors.panel},typeSelected:{borderWidth:2,borderColor:colors.primary},typeText:{color:colors.text,fontWeight:'800'},cover:{height:150,alignItems:'center',justifyContent:'center',gap:8,borderRadius:8,overflow:'hidden',backgroundColor:colors.panel},coverImage:{width:'100%',height:'100%'},input:{color:colors.text,padding:14,borderRadius:8,borderWidth:1,borderColor:colors.border,backgroundColor:colors.panel},area:{height:112,textAlignVertical:'top'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:14,borderRadius:8,backgroundColor:colors.panel},label:{color:colors.text,fontWeight:'800'},muted:{color:colors.muted,fontSize:12},preview:{minHeight:280,alignItems:'center',justifyContent:'center',gap:10,borderRadius:8,backgroundColor:colors.panel},previewImage:{width:'100%',height:210},button:{alignItems:'center',padding:16,borderRadius:8,backgroundColor:colors.primary},buttonText:{color:colors.text,fontWeight:'900'} });
